sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -t harishdurga/docker-tutorial-react -f Dockerfile.dev  .
script:
  - docker run -e CI=true harishdurga/docker-tutorial-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-tutorial-react"
  env: "DockerTutorialReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-892292758783"
  bucket_path: "docker-tutorial-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
